# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170425_2019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
            ],
        ),
    ]
